// <auto-generated />
using System;
using KolayKobi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KolayKobi.Api.migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813123046_AddBulkToolPurchase")]
    partial class AddBulkToolPurchase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KolayKobi.Api.Data.Models.PaymentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IyzicoPaymentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IyzicoToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ToolId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ToolIds")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UsesPerTool")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.HasIndex("IyzicoToken");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentOrders");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PeriodDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PeriodEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PeriodStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodType")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceMonthly")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PricePerUse")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UsagePerToolPerMonth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Her araç için ayda 3 kullanım",
                            IsActive = true,
                            Name = "Ücretsiz",
                            PeriodType = 0,
                            PriceMonthly = 0m,
                            Type = 0,
                            UsagePerToolPerMonth = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tüm araçlarda ayda 10 kullanım",
                            IsActive = true,
                            Name = "Standart",
                            PeriodType = 0,
                            PriceMonthly = 199m,
                            Type = 1,
                            UsagePerToolPerMonth = 10
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tüm araçlarda ayda 25 kullanım",
                            IsActive = true,
                            Name = "Premium",
                            PeriodType = 0,
                            PriceMonthly = 399m,
                            Type = 2,
                            UsagePerToolPerMonth = 25
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kullandıkça öde",
                            IsActive = true,
                            Name = "Kurumsal",
                            PeriodType = 0,
                            PriceMonthly = 0m,
                            PricePerUse = 15m,
                            Type = 3
                        });
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IyzicoSubscriptionId")
                        .HasColumnType("text");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.ToolPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PriceMonthly")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ToolId")
                        .IsUnique();

                    b.ToTable("ToolPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PriceMonthly = 9m,
                            ToolId = "gorunurluk-skoru",
                            ToolName = "İşletme Görünürlük Skoru",
                            UpdatedAt = new DateTime(2026, 8, 13, 12, 30, 46, 521, DateTimeKind.Utc).AddTicks(2940)
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PriceMonthly = 9m,
                            ToolId = "musteri-persona",
                            ToolName = "Müşteri Persona Oluşturucu",
                            UpdatedAt = new DateTime(2026, 8, 13, 12, 30, 46, 521, DateTimeKind.Utc).AddTicks(3430)
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            PriceMonthly = 29m,
                            ToolId = "icerik-takvimi",
                            ToolName = "30 Günlük İçerik Takvimi",
                            UpdatedAt = new DateTime(2026, 8, 13, 12, 30, 46, 521, DateTimeKind.Utc).AddTicks(3430)
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            PriceMonthly = 9m,
                            ToolId = "whatsapp-satis",
                            ToolName = "WhatsApp Satış Script Üretici",
                            UpdatedAt = new DateTime(2026, 8, 13, 12, 30, 46, 521, DateTimeKind.Utc).AddTicks(3430)
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            PriceMonthly = 9m,
                            ToolId = "reklam-butce",
                            ToolName = "Reklam Bütçe Dağıtıcı",
                            UpdatedAt = new DateTime(2026, 8, 13, 12, 30, 46, 521, DateTimeKind.Utc).AddTicks(3430)
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            PriceMonthly = 9m,
                            ToolId = "musteri-geri-donus",
                            ToolName = "Müşteri Geri Dönüş Senaryosu",
                            UpdatedAt = new DateTime(2026, 8, 13, 12, 30, 46, 521, DateTimeKind.Utc).AddTicks(3430)
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            PriceMonthly = 9m,
                            ToolId = "rakip-analiz",
                            ToolName = "Rakip Analiz Panosu",
                            UpdatedAt = new DateTime(2026, 8, 13, 12, 30, 46, 521, DateTimeKind.Utc).AddTicks(3430)
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            PriceMonthly = 9m,
                            ToolId = "chatbot-senaryo",
                            ToolName = "Chatbot Senaryo Hazırlayıcı",
                            UpdatedAt = new DateTime(2026, 8, 13, 12, 30, 46, 521, DateTimeKind.Utc).AddTicks(3430)
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            PriceMonthly = 9m,
                            ToolId = "ai-gorunurluk",
                            ToolName = "AI Görünürlük Takipçisi",
                            UpdatedAt = new DateTime(2026, 8, 13, 12, 30, 46, 521, DateTimeKind.Utc).AddTicks(3430)
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            PriceMonthly = 9m,
                            ToolId = "viral-video",
                            ToolName = "Viral Video Uyarlayıcı",
                            UpdatedAt = new DateTime(2026, 8, 13, 12, 30, 46, 521, DateTimeKind.Utc).AddTicks(3430)
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            PriceMonthly = 29m,
                            ToolId = "trend-video",
                            ToolName = "Trend Video Bulucu",
                            UpdatedAt = new DateTime(2026, 8, 13, 12, 30, 46, 521, DateTimeKind.Utc).AddTicks(3430)
                        });
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.ToolPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IyzicoPaymentId")
                        .HasColumnType("text");

                    b.Property<int?>("MonthlyLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("UsesGranted")
                        .HasColumnType("integer");

                    b.Property<int>("UsesRemaining")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ToolPurchases");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.ToolResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("ToolResults");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.ToolUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("LimitAtTime")
                        .HasColumnType("integer");

                    b.Property<string>("PlanNameAtTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UsageCountBefore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ToolId", "UsedAt");

                    b.ToTable("ToolUsageLogs");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EmailVerificationExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.PaymentOrder", b =>
                {
                    b.HasOne("KolayKobi.Api.Data.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId");

                    b.HasOne("KolayKobi.Api.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.Subscription", b =>
                {
                    b.HasOne("KolayKobi.Api.Data.Models.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KolayKobi.Api.Data.Models.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("KolayKobi.Api.Data.Models.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.ToolPurchase", b =>
                {
                    b.HasOne("KolayKobi.Api.Data.Models.User", "User")
                        .WithMany("ToolPurchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.ToolResult", b =>
                {
                    b.HasOne("KolayKobi.Api.Data.Models.User", "User")
                        .WithMany("ToolResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.ToolUsageLog", b =>
                {
                    b.HasOne("KolayKobi.Api.Data.Models.User", "User")
                        .WithMany("UsageLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.Plan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("KolayKobi.Api.Data.Models.User", b =>
                {
                    b.Navigation("Subscription");

                    b.Navigation("ToolPurchases");

                    b.Navigation("ToolResults");

                    b.Navigation("UsageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
